/**
 * Which message namespaces each route actually needs.
 *
 * Why this exists: `getRequestConfig` used to load all 34 namespaces on every
 * request, and `app/layout.tsx` hands the result to `NextIntlClientProvider` —
 * a client component. So the whole catalog (290 KB for `es`) was serialized
 * into the RSC flight payload inlined in *every* page's HTML. Measured on
 * production `/login`: 284 KB of inline script for a page that needs ~7 KB of
 * strings. Scoping the load per route cuts that by 55-97% depending on route.
 *
 * The table below was generated by walking the real import graph from every
 * `app/**` entry point (page + all ancestor layouts) and unioning the
 * `useTranslations('x')` / `getTranslations('x')` namespaces reachable from it.
 * Regenerate it the same way if routes move — or, when in doubt, add the
 * namespace: over-including costs bytes, under-including renders raw keys.
 *
 * Matching is longest-literal-prefix. Anything whose first segment is not a
 * known top-level route is treated as `/[username]` (the app's only root-level
 * catch-all), and anything else unrecognised falls back to the full catalog.
 */

/**
 * Request header the proxy stamps with the incoming pathname. Next.js does not
 * expose the path to `getRequestConfig`, and the root layout can't read it
 * either, so the proxy threads it through `NextResponse.next({ request })`.
 */
export const PATHNAME_HEADER = 'x-yb-pathname';

export const ALL_NAMESPACES = [
  'admin', 'article', 'askme', 'auth', 'avatar', 'blogs', 'businesses', 'chat',
  'cities', 'clubes', 'common', 'communities', 'familias', 'feed', 'foro',
  'friendships', 'grupos', 'header', 'landing', 'legal', 'liveStream', 'musica',
  'nav', 'notification', 'pages', 'player', 'portals', 'professional', 'profile',
  'profiles', 'search', 'settings', 'stories', 'verification', 'watch',
] as const;

export type Namespace = (typeof ALL_NAMESPACES)[number];

/**
 * Mounted on every authenticated `(app)` route by `application-layout-client`
 * and `(app)/layout.tsx`: header, sidebars, chat tray, notification bell,
 * friend rails, plus the global media player.
 *
 * `player` (820 B) rather than `musica` (46 KB): the player components live in
 * the music feature but are mounted app-wide, so their ~20 strings were
 * dragging the entire music catalog into every signed-in page. Only genuine
 * `/musica/**` routes ask for `musica` now.
 */
const APP_SHELL: Namespace[] = [
  'avatar', 'chat', 'friendships', 'header', 'nav', 'notification', 'player',
  'search', 'verification',
];

/** The `(auth)` group has its own featherweight layout — no app shell at all. */
const AUTH_ONLY: Namespace[] = ['auth', 'avatar', 'common', 'legal'];

/** `/[username]` and its subroutes (`/friends`, `/posts/...`). */
const PROFILE_ROUTE: Namespace[] = [...APP_SHELL, 'feed', 'profile'];

const shell = (...extra: Namespace[]): Namespace[] => [...APP_SHELL, ...extra];

/** Longest-literal-prefix wins, so order here is irrelevant. */
const ROUTE_NAMESPACES: ReadonlyArray<readonly [string, Namespace[]]> = [
  // (auth)
  ['/login', AUTH_ONLY],
  ['/signup', AUTH_ONLY],
  ['/forgot-password', AUTH_ONLY],
  ['/reset-password', AUTH_ONLY],
  ['/verify-email', AUTH_ONLY],
  ['/auth', AUTH_ONLY],

  // (legal) + standalone public artifacts
  ['/normativa', ['legal', 'avatar', 'common']],
  ['/verification', ['legal', 'common']],

  // (admin)
  ['/admin', ['admin', 'common']],
  ['/admin/ciudades', ['admin', 'cities', 'common']],
  ['/admin/foros', ['admin', 'foro', 'common']],
  ['/admin/chat-publico', ['admin', 'foro', 'common']],
  ['/admin/music', ['admin', 'musica', 'professional', 'common']],

  // (app) — feed and its subtrees
  ['/feed', shell('feed', 'stories')],
  ['/feed/amigos', shell('feed')],
  ['/feed/article', shell('article')],
  ['/feed/blogs', shell('blogs', 'feed', 'foro', 'musica')],
  ['/feed/businesses', shell('businesses')],
  ['/feed/chat-publico', shell()],
  ['/feed/clubs', shell('clubes')],
  ['/feed/comunidades', shell('communities', 'foro', 'article')],
  ['/feed/familias', shell('familias', 'common')],
  ['/feed/friends', shell('feed')],
  ['/feed/friendships', shell('feed', 'profile')],
  ['/feed/grupos', shell('grupos')],
  ['/feed/mis-negocios', shell('businesses')],
  ['/feed/portals', shell('portals')],
  ['/feed/post', shell('feed')],
  ['/feed/professional-profile', shell('professional')],
  ['/feed/profile', shell('feed', 'profile')],
  ['/feed/profiles', shell('profiles')],
  ['/feed/videos', shell('profile')],

  // (app) — everything else
  ['/ajustes', shell('settings', 'admin')],
  ['/chat', shell()],
  ['/cities', shell('cities', 'businesses')],
  ['/foro', shell('foro')],
  ['/grupos', shell('grupos')],
  ['/insignias', shell()],
  ['/musica', shell('musica', 'feed')],
  ['/musica/blog', shell('musica', 'blogs', 'feed', 'foro')],
  ['/musica/clubes', shell('musica', 'foro', 'clubes', 'article')],
  ['/notifications', shell()],
  ['/paginas', shell('pages', 'businesses', 'feed')],
  ['/professional-services', shell('professional')],
  ['/search', shell()],
  ['/stories', shell('stories')],
  ['/watch', shell('watch', 'liveStream')],

  // El Umbral (marketing stunt) — standalone page, all copy hardcoded es.
  ['/umbral', ['common']],

  // Secondary platforms migrated in — their own layouts, no app shell.
  ['/negocios', ['feed', 'businesses', 'common']],
  ['/escuelas', ['common']],
  ['/artistas', ['common']],
  ['/artista', ['common']],
  ['/campanas', ['common']],
  ['/eventos', ['common']],
  ['/manager', ['common']],
  ['/oportunidades', ['common']],
  ['/portafolio', ['common']],
  ['/programas', ['common']],
  ['/promociones', ['common']],
];

/** First segment of every route the app actually declares. Anything else is a username. */
const KNOWN_TOP_LEVEL = new Set(
  ROUTE_NAMESPACES.map(([prefix]) => prefix.split('/')[1]).filter(Boolean),
);

/**
 * Namespaces to load for `pathname`. Falls back to the full catalog when the
 * path can't be classified (which is correct-but-heavy, never broken).
 */
export function namespacesForPath(pathname: string | null | undefined): readonly Namespace[] {
  if (!pathname) return ALL_NAMESPACES;

  const segments = pathname.split('/').filter(Boolean);
  if (segments.length === 0) return ALL_NAMESPACES; // `/` only ever redirects

  if (!KNOWN_TOP_LEVEL.has(segments[0])) return PROFILE_ROUTE;

  let best: Namespace[] | null = null;
  let bestLength = -1;
  for (const [prefix, namespaces] of ROUTE_NAMESPACES) {
    if (pathname !== prefix && !pathname.startsWith(`${prefix}/`)) continue;
    if (prefix.length > bestLength) {
      best = namespaces;
      bestLength = prefix.length;
    }
  }
  return best ?? ALL_NAMESPACES;
}
