import { FamilyTreeData } from './types';

export const mockFamilyTree: FamilyTreeData = {
  rootMemberId: 'self',
  members: [
    // Self
    {
      id: 'self',
      name: 'Tú',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=self',
      birthYear: 1990,
      gender: 'male',
      relationship: 'self',
      generation: 0,
      parents: ['father', 'mother'],
    },
    // Parents
    {
      id: 'father',
      name: 'Juan Pérez',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=father',
      birthYear: 1965,
      gender: 'male',
      relationship: 'parent',
      generation: -1,
      parents: ['grandfather-p', 'grandmother-p'],
      spouse: 'mother',
    },
    {
      id: 'mother',
      name: 'María García',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mother',
      birthYear: 1967,
      gender: 'female',
      relationship: 'parent',
      generation: -1,
      parents: ['grandfather-m', 'grandmother-m'],
      spouse: 'father',
    },
    // Paternal Grandparents
    {
      id: 'grandfather-p',
      name: 'Carlos Pérez',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=grandfatherp',
      birthYear: 1940,
      deathYear: 2010,
      gender: 'male',
      relationship: 'grandparent',
      generation: -2,
      spouse: 'grandmother-p',
    },
    {
      id: 'grandmother-p',
      name: 'Ana López',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=grandmotherp',
      birthYear: 1942,
      gender: 'female',
      relationship: 'grandparent',
      generation: -2,
      spouse: 'grandfather-p',
    },
    // Maternal Grandparents
    {
      id: 'grandfather-m',
      name: 'Roberto García',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=grandfatherm',
      birthYear: 1945,
      gender: 'male',
      relationship: 'grandparent',
      generation: -2,
      spouse: 'grandmother-m',
    },
    {
      id: 'grandmother-m',
      name: 'Isabel Fernández',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=grandmotherm',
      birthYear: 1947,
      gender: 'female',
      relationship: 'grandparent',
      generation: -2,
      spouse: 'grandfather-m',
    },
    // Siblings
    {
      id: 'sibling1',
      name: 'Laura Pérez',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sister',
      birthYear: 1988,
      gender: 'female',
      relationship: 'sibling',
      generation: 0,
      parents: ['father', 'mother'],
    },
    // Children
    {
      id: 'child1',
      name: 'Sofía',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=daughter',
      birthYear: 2015,
      gender: 'female',
      relationship: 'child',
      generation: 1,
      parents: ['self'],
    },
    {
      id: 'child2',
      name: 'Diego',
      photo: 'https://api.dicebear.com/7.x/avataaars/svg?seed=son',
      birthYear: 2017,
      gender: 'male',
      relationship: 'child',
      generation: 1,
      parents: ['self'],
    },
  ],
};
