// Build-time generator: docs/legal/*.md  ->  src/features/legal/content/legal-docs.generated.ts
//
// The app has no runtime markdown parser and does not read files at runtime, so we
// convert the legal source-of-truth to HTML here and commit the generated module.
// Re-run after editing any docs/legal/*.md:   pnpm legal:build   (then commit the output)
//
// Each heading gets a stable, accent-stripped id so pages can deep-link to a section
// (e.g. the privacy section of the Contrato -> #parte-vi-politica-de-privacidad-extendida).

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

import MarkdownIt from 'markdown-it';

const ROOT = process.cwd();
const SRC_DIR = join(ROOT, 'docs', 'legal');
const OUT_FILE = join(ROOT, 'src', 'features', 'legal', 'content', 'legal-docs.generated.ts');

// User-facing presentation metadata. The body comes verbatim from the .md source.
const DOCS = [
  {
    slug: 'terminos',
    file: 'contrato-usuario.md',
    title: 'Términos y Condiciones',
    subtitle: 'Contrato de Usuario y Términos y Condiciones de Uso',
    updatedAt: '2026',
  },
  {
    slug: 'normas-comunitarias',
    file: 'manual-convivencia.md',
    title: 'Normas Comunitarias',
    subtitle: 'Manual de Convivencia, Gobernanza y Reglamento de Uso',
    updatedAt: '19 de mayo de 2026',
  },
  {
    slug: 'reglamento',
    file: 'macro-reglamento.md',
    title: 'Reglamento General',
    subtitle: 'Macro Reglamento de Regulación, Gobernanza y Convivencia Digital',
    updatedAt: '2026',
  },
];

function slugify(text) {
  return text
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '') // strip diacritics (á -> a, ñ -> n)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const md = new MarkdownIt({ html: false, linkify: false, typographer: false });

// Inject a stable id on every heading so sections are deep-linkable.
md.core.ruler.push('heading_ids', (state) => {
  const used = new Map();
  for (let i = 0; i < state.tokens.length; i++) {
    const tok = state.tokens[i];
    if (tok.type !== 'heading_open') continue;
    const inline = state.tokens[i + 1];
    if (!inline || inline.type !== 'inline') continue;
    let slug = slugify(inline.content);
    if (!slug) continue;
    const n = used.get(slug) ?? 0; // de-dupe collisions
    used.set(slug, n + 1);
    if (n > 0) slug = `${slug}-${n}`;
    tok.attrSet('id', slug);
  }
});

/** Drop the H1 + dev-facing front-matter blockquote: keep everything after the first `---` rule. */
function extractBody(raw) {
  const idx = raw.indexOf('\n---\n');
  const body = idx === -1 ? raw : raw.slice(idx + '\n---\n'.length);
  return body.trim();
}

const entries = DOCS.map((doc) => {
  const raw = readFileSync(join(SRC_DIR, doc.file), 'utf8');
  const html = md.render(extractBody(raw));
  return { ...doc, html };
});

const banner = `// AUTO-GENERATED by scripts/build-legal.mjs — DO NOT EDIT BY HAND.
// Source of truth: docs/legal/*.md. Regenerate with: pnpm legal:build
`;

const body = `export interface LegalDoc {
  slug: string;
  title: string;
  subtitle: string;
  updatedAt: string;
  html: string;
}

export const LEGAL_DOCS = ${JSON.stringify(
  Object.fromEntries(entries.map((e) => [e.slug, e])),
  null,
  2,
)} as const satisfies Record<string, LegalDoc>;

export type LegalSlug = keyof typeof LEGAL_DOCS;

export const LEGAL_SLUGS = ${JSON.stringify(entries.map((e) => e.slug))} as const;
`;

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, banner + '\n' + body, 'utf8');

console.log(`[build-legal] wrote ${OUT_FILE}`);
for (const e of entries) {
  console.log(`  - ${e.slug}: ${e.html.length} bytes of HTML (${e.title})`);
}
