export type UserBadgeJoinedRow = {
  id: string;
  awarded_at: string;
  reason: string | null;
  acceptance_status: 'pending' | 'accepted' | 'declined';
  is_hidden: boolean;
  badge: {
    id: string;
    slug: string;
    name: string;
    description: string;
    icon_cf_image_id: string | null;
    category: string;
    slot: 'insignia' | 'badge';
    tier: string | null;
    is_system: boolean;
    visibility: 'public' | 'private';
    deleted_at: string | null;
  } | null;
};

export type DbProfile = {
  id: string;
  username: string | null;
  first_name: string | null;
  middle_name: string | null;
  last_name: string | null;
  second_last_name: string | null;
  display_name: string | null;
  bio: string | null;
  website: string | null;
  birth_date: string | null;
  gender: 'MALE' | 'FEMALE' | 'OTHER' | string | null;
  country: string | null;
  state: string | null;
  city: string | null;
  hometown: string | null;
  phone_number: string | null;
  avatar_url: string | null;
  cover_photo_url: string | null;
  cover_offset_x: number | null;
  cover_offset_y: number | null;
  cover_zoom: number | null;
  relationship_status: string | null;
  interests: string[] | null;
  languages: string[] | null;
  friends_count: number | null;
  followers_count: number | null;
  posts_count: number | null;
  photos_count: number | null;
  videos_count: number | null;
  work_experience: unknown;
  education: unknown;
  study_place: string | null;
  work_place: string | null;
  work_position: string | null;
  work_verified: boolean | null;
  occupation: string | null;
  residence_country: string | null;
  residence_state: string | null;
  residence_city: string | null;
  birth_place: string | null;
  is_verified: boolean | null;
  verification_status: 'unstarted' | 'pending' | 'approved' | 'rejected' | null;
  pioneer_number: number | null;
  unique_id_code: string | null;
  facebook_url: string | null;
  instagram_url: string | null;
  twitter_url: string | null;
  linkedin_url: string | null;
  github_url: string | null;
  favorite_movies: string[] | null;
  favorite_books: string[] | null;
  favorite_games: string[] | null;
  favorite_tv_shows: string[] | null;
  favorite_music: string[] | null;
  created_at: string;
  updated_at: string;
};
