/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/music-cache/wrangler.jsonc --include-runtime=false --env-interface=MusicCacheEnv workers/music-cache/env.d.ts` (hash: 5703051f52b66871e0c149135a3f6097)
interface __BaseEnv_MusicCacheEnv {
	MUSIC: R2Bucket;
	MUSIC_CACHE_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_MusicCacheEnv {}
}
interface MusicCacheEnv extends __BaseEnv_MusicCacheEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MUSIC_CACHE_SECRET">> {}
}
