/**
 * Heroicons → Lucide compatibility shim.
 *
 * Re-exports every heroicon name used in the codebase as a direct alias of the
 * equivalent `lucide-react` icon, so call sites like
 * `<ChevronRightIcon className="h-5 w-5" />` keep working unchanged across the
 * 612 files that import from here.
 *
 * Why a plain `export { X as YIcon }` and not a wrapper component: these are
 * static re-exports, so bundlers tree-shake down to only the icons a route
 * actually renders. The previous implementation wrapped `@iconify/react`,
 * which fetched every glyph at runtime from api.iconify.design — that meant a
 * third-party DNS+TLS+RTT on the critical path and a visible blank-icon flash
 * on every cold load. Lucide ships the SVG paths in the bundle, so icons paint
 * with the first frame and work offline.
 *
 * Adding an icon: find the Lucide name (https://lucide.dev/icons), then add a
 * `LucideName as SomethingIcon` line below, keeping the list alphabetical by
 * the exported alias where practical.
 */

export {
  GraduationCap as AcademicCapIcon,
  SlidersHorizontal as AdjustmentsHorizontalIcon,
  ArrowLeft as ArrowLeftIcon,
  RotateCw as ArrowPathIcon,
  ArrowRight as ArrowRightIcon,
  ExternalLink as ArrowTopRightOnSquareIcon,
  Upload as ArrowUpTrayIcon,
  Maximize as ArrowsPointingOutIcon,
  Menu as Bars3Icon,
  FlaskConical as BeakerIcon,
  Bell as BellIcon,
  Bell as BellSolidIcon,
  BookOpen as BookOpenIcon,
  Bookmark as BookmarkIcon,
  Briefcase as BriefcaseIcon,
  Store as BuildingStorefrontIcon,
  Cake as CakeIcon,
  Calendar as CalendarIcon,
  Camera as CameraIcon,
  BarChart3 as ChartBarIcon,
  MessageCircle as ChatBubbleLeftIcon,
  MessagesSquare as ChatBubbleLeftRightIcon,
  MessageCircle as ChatBubbleOvalLeftIcon,
  BadgeCheck as CheckBadgeIcon,
  CheckCircle2 as CheckCircleIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  Clipboard as ClipboardDocumentIcon,
  Clock as ClockIcon,
  CloudUpload as CloudArrowUpIcon,
  Code as CodeBracketIcon,
  Settings as Cog6ToothIcon,
  DollarSign as CurrencyDollarIcon,
  FileDown as DocumentArrowDownIcon,
  File as DocumentIcon,
  FileText as DocumentTextIcon,
  MoreHorizontal as EllipsisHorizontalCircleIcon,
  MoreHorizontal as EllipsisHorizontalIcon,
  MoreVertical as EllipsisVerticalIcon,
  Mail as EnvelopeIcon,
  AlertCircle as ExclamationCircleIcon,
  AlertTriangle as ExclamationTriangleIcon,
  Eye as EyeIcon,
  EyeOff as EyeSlashIcon,
  Frown as FaceFrownIcon,
  Smile as FaceSmileIcon,
  Flame as FireIcon,
  Folder as FolderIcon,
  FolderPlus as FolderPlusIcon,
  Filter as FunnelIcon,
  Image as GifIcon,
  Globe as GlobeAltIcon,
  Globe2 as GlobeAmericasIcon,
  ThumbsUp as HandThumbUpIcon,
  Hash as HashtagIcon,
  Heart as HeartIcon,
  Heart as HeartSolidIcon,
  Home as HomeIcon,
  Info as InformationCircleIcon,
  KeyRound as KeyIcon,
  Languages as LanguageIcon,
  Lightbulb as LightBulbIcon,
  Link as LinkIcon,
  List as ListBulletIcon,
  Lock as LockClosedIcon,
  LockOpen as LockOpenIcon,
  Search as MagnifyingGlassIcon,
  ZoomOut as MagnifyingGlassMinusIcon,
  ZoomIn as MagnifyingGlassPlusIcon,
  Map as MapIcon,
  MapPin as MapPinIcon,
  Mic as MicrophoneIcon,
  Minus as MinusIcon,
  Moon as MoonIcon,
  Music as MusicalNoteIcon,
  Newspaper as NewspaperIcon,
  Send as PaperAirplaneIcon,
  Pencil as PencilIcon,
  SquarePen as PencilSquareIcon,
  Phone as PhoneIcon,
  Image as PhotoIcon,
  Play as PlayIcon,
  Plus as PlusIcon,
  Share2 as ShareIcon,
  ShieldCheck as ShieldCheckIcon,
  Signal as SignalIcon,
  SignalZero as SignalSlashIcon,
  Sparkles as SparklesIcon,
  Grid2x2 as Squares2X2Icon,
  Star as StarIcon,
  Star as StarSolidIcon,
  Sun as SunIcon,
  Table as TableCellsIcon,
  Tag as TagIcon,
  Trash2 as TrashIcon,
  Trophy as TrophyIcon,
  UserCircle as UserCircleIcon,
  Users as UserGroupIcon,
  User as UserIcon,
  UserMinus as UserMinusIcon,
  UserPlus as UserPlusIcon,
  Users as UsersIcon,
  Video as VideoCameraIcon,
  Wifi as WifiIcon,
  XCircle as XCircleIcon,
  X as XMarkIcon,
  Download as ArrowDownTrayIcon,
  RotateCcwSquare as ArrowPathRoundedSquareIcon,
  TrendingUp as ArrowTrendingUpIcon,
  Bold as BoldIcon,
  Zap as BoltIcon,
  Library as BuildingLibraryIcon,
  Building2 as BuildingOffice2Icon,
  Building as BuildingOfficeIcon,
  CalendarDays as CalendarDaysIcon,
  MessageSquareText as ChatBubbleBottomCenterTextIcon,
  Monitor as ComputerDesktopIcon,
  Smartphone as DevicePhoneMobileIcon,
  Film as FilmIcon,
  Flag as FlagIcon,
  Hand as HandRaisedIcon,
  Home as HomeModernIcon,
  Inbox as InboxArrowDownIcon,
  Italic as ItalicIcon,
  LifeBuoy as LifebuoyIcon,
  Megaphone as MegaphoneIcon,
  Paintbrush as PaintBrushIcon,
  Pause as PauseIcon,
  HelpCircle as QuestionMarkCircleIcon,
  ListOrdered as QueueListIcon,
  Layers as RectangleStackIcon,
  Rocket as RocketLaunchIcon,
  Scale as ScaleIcon,
  Server as ServerIcon,
  ShoppingBag as ShoppingBagIcon,
  Volume2 as SpeakerWaveIcon,
  VolumeX as SpeakerXMarkIcon,
  Square as StopIcon,
  Ticket as TicketIcon,
  Tv as TvIcon,
  Wrench as WrenchScrewdriverIcon,
  PhoneOff as PhoneXMarkIcon,
  MicOff as MicrophoneSlashIcon,
  VideoOff as VideoCameraSlashIcon,
} from 'lucide-react'
